import Head from "next/head";

import Navbar from "../components/Navbar";
import Header from "../components/Header";
import Skills from "../components/Skills";
import { useState } from "react";
import Footer from "../components/Footer";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mikuláš Richter Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-30 dark:bg-gray-800">
        <section className="min-h-screen">
          <Navbar isDark={darkMode} onDarkModeChange={setDarkMode} />
          {/* onDarkModeChange === setDarkMode */}
          <button
            type="button"
            className="btn"
            onClick={() => {
              console.log("his");
              setDarkMode(false);
            }}
          ></button>
          <div className="pt-8">
            <Header />
          </div>
          <div className="pt-8">
            <Skills />
          </div>
          <div>
            <Footer />
          </div>
        </section>
        <section></section>
      </main>
    </div>
  );
}
